version: "3.8"
services:
  atlas:
    image: ceceradio/atlas:latest
    build: .
    networks:
      - atlas
    platform: linux/amd64
    restart: always
    depends_on:
      - db
      - redis
    env_file:
      - .env.next
      - .env.api
  nginx:
    image: nginx:mainline-alpine
    restart: always
    hostname: local.atlasai.zone
    networks:
      - atlas
    ports:
      - "880:80"
      - "8443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certs:/etc/ssl/certs
  db:
    image: postgres:14.5-alpine
    restart: always
    networks:
      - atlas
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    networks:
      - atlas
    ports:
      - "6379:6379"
volumes:
  db:
    driver: local
  nginx:
    driver: local
  certs:
    driver: local
networks:
  atlas:
