server {
    listen 80;
    server_name chocolate.local; 
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;

    server_name chocolate.local;
    ssl_certificate /etc/ssl/certs/chocolate.local.cert;
    ssl_certificate_key /etc/ssl/certs/chocolate.local.key;

    resolver 127.0.0.11 valid=10s ipv6=off;

    location /ws/ {
        proxy_pass http://atlas:3002/;
        proxy_http_version 1.1;
        proxy_read_timeout 7d;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_cache_bypass $http_upgrade;
        expires -1;
    }
    location /api/ {
        proxy_pass http://atlas:3001/;
        proxy_read_timeout 600s;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_cache_bypass $http_upgrade;
        expires -1;
    }
    location /_next/webpack-hmr {
        proxy_pass http://atlas:3003/_next/webpack-hmr;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_read_timeout 7d;
        expires -1;
    }
    location / {
        proxy_pass http://atlas:3003/;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_cache_bypass $http_upgrade;
        expires -1;
    }
}